vich_uploader:
    db_driver: orm
    mappings:
        file_upload:
            uri_prefix: /uploads/files
            upload_destination: '%kernel.project_dir%/public/uploads/files'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
