vich_uploader:
    db_driver: orm
    mappings:
        post_files:
            uri_prefix: /uploads/posts
            upload_destination: '%kernel.project_dir%/public/uploads/posts'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
